services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: refurnish
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - ./backend/dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 2s
      retries: 10
      timeout: 2s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/refurnish?sslmode=disable
      JWT_SECRET: supersecret123

    volumes:
      - ./backend/migrations:/app/migrations
    depends_on:
      db:
        condition: service_healthy
